### ISSUE TITLE
App Crashes after Deleting the Note

### ISSUE THREAD

**Issue by Aditya13s** [Aditya13s/DailyNotes#1]
When we add more than one note and delete the last note. Note deletes and app crashes immediately.

**Comment by kldMohammed** [comment]
Can you provide the stack trace

**Comment by Aditya13s** [comment]
You can clone this repository and see yourself

**Comment by Aditya13s** [comment]
> Can you provide the stack trace
![image](https://user-images.githubusercontent.com/77337791/203507797-38a374b5-15f9-41c3-a6af-5e3b78845822.png)

**Comment by kldMohammed** [comment]
@Aditya13s I can't reproduce it.

it works fine on my device
